# Generated by Django 3.2.8 on 2021-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=500, verbose_name='Company Name')),
                ('Company_location', models.CharField(max_length=500, verbose_name='Company location')),
                ('Company_domain', models.CharField(max_length=500, verbose_name='Company domain')),
                ('Email', models.EmailField(max_length=500, verbose_name='Email')),
                ('Password', models.CharField(max_length=500, verbose_name='Password')),
                ('Phone_no', models.IntegerField(verbose_name='Phone no')),
            ],
        ),
    ]
