# Generated by Django 3.2.8 on 2021-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('company_domain', models.CharField(max_length=25)),
                ('company_location', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phone_no', models.IntegerField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
