# Generated by Django 4.0.1 on 2022-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=25)),
                ('company_Id', models.IntegerField()),
                ('domain', models.CharField(max_length=25)),
                ('ready_to_relocate', models.BooleanField()),
                ('current_loc', models.CharField(max_length=25)),
                ('resume_link', models.URLField()),
                ('notice_period', models.DateField()),
                ('laidoffdate', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
