# Generated by Django 4.0.1 on 2022-02-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='comp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='company_Id',
            new_name='company_id',
        ),
    ]
